### ISSUE TITLE
Text kerning issue in Zing editor

### ISSUE THREAD

**Issue by michaelahokas** [aaronkennedy/ZingElements#201]
![screen shot 2014-09-27 at 13 51 42](https://cloud.githubusercontent.com/assets/8209164/4429675/cecffb5e-45f9-11e4-91a3-5afc3f1c5a4a.png)

The kerning is too tight here

**Comment by aaronkennedy** [comment]
OS X TextEdit renders it the same way. Lodge a bug with the font designer ;)
