### ISSUE TITLE
Have a rotate Image function on the skin

### ISSUE THREAD

**Issue by custa1200** [aaronkennedy/ZingElements#335]
Would be good if there was a way to adjust the skin/simulator directly on it. 
i.e maybe a rotate button as an example?

**Comment by aaronkennedy** [comment]
Are the keyboard shortcuts not sufficient?

**Comment by custa1200** [comment]
For me, personally, nope. I am not reply a keyboard fiend and prefer to have things more visual

**Comment by custa1200** [comment]
*really.
