### ISSUE TITLE
Labs keeps freezing up when Ishtar restarts

### ISSUE THREAD

**Issue by designker** [aaronkennedy/ZingElements#389]
While typing after awhile Labs starts to freeze up when Ishtar is building its UI.

**Comment by aaronkennedy** [comment]
When this happens, does closing and reopening the simulator fix it?

**Comment by designker** [comment]
Yes

**Comment by aaronkennedy** [comment]
This is caused by leaks in the simulator agent. I am slowly fixing them. There is no real need for a general bug in this case.
