### ISSUE TITLE
Mismatched loop iterators can cause a crash

### ISSUE THREAD

**Issue by michaelahokas** [aaronkennedy/ZingElements#413]
If you do something like:

    for (var i = 0; i < 100; i++) {
        for (var ii = 0; ii < 100; i++) { // notice that here the inner loop increments i not ii 
        }
    }

it crashes the app

**Comment by aaronkennedy** [comment]
This isn't a crash, it is an infinite loop which then causes the simulator to be killed for being unresponsive. Infinite loops do need to be detected, but that is a different bug :)
