### ISSUE TITLE
App does not appear to go to sleep when in the background on Android

### ISSUE THREAD

**Issue by designker** [aaronkennedy/ZingElements#477]
Some beta users are seeing huge data usage. The 2.75GB user says they only used the app a couple of hours and so the rest of the time it should have been in the background doing nothing.

![154e29b65f0fa8556642](https://cloud.githubusercontent.com/assets/1957186/15529637/653d63fc-2257-11e6-86de-0ae7327adccd.png)
![screenshot_20160524-105821_720](https://cloud.githubusercontent.com/assets/1957186/15529639/653e43b2-2257-11e6-8073-00c6787adc9f.png)
![154e29b389df70d8da51](https://cloud.githubusercontent.com/assets/1957186/15529638/653dbb36-2257-11e6-9860-ec1158fc35b7.png)

**Comment by aaronkennedy** [comment]
Can't reproduce
