### ISSUE TITLE
Hard Freeze ("Loading icon of death") when navigating to the "States" section

### ISSUE THREAD

**Issue by v-fedorov** [aaronkennedy/ZingElements#479]
My 2010 Macbook has a corrupted Nvidia card which causes the machine to randomly panic and restart.
To bypass this I am using gfxCardStatus so i can "Lock" my gpu to only use the Integrated Intel HD card.

For some reason if I try to go into the States page, specifically when a Gesture has been created, it causes my machine to freeze forcing a hard restart.
If I don't have any gestures created then I can be on the page with no problem, also if I remove the lock on the gpu then everything works fine.

Something in the UI seems to be forcing my macbook to switch to the discrete Nvidia card while at the same time gfxCardStatus prevents it from completely switching over.

Its hard getting the crash log since I am forcing the restart but ill try pinpointing the exact error, just wanted to provide a few more details first

Hopefully this will help
```
6/18/16 5:04:10.000 PM kernel[0]: process Zing Elements La[4339] caught causing excessive wakeups. Observed wakeups rate (per sec): 2923; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45244

6/18/16 5:04:11.021 PM com.apple.xpc.launchd[1]: (com.apple.ReportCrash[4340]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash

6/18/16 5:04:11.036 PM ReportCrash[4340]: Invoking spindump for pid=4339 wakeups_rate=2923 duration=16 because of excessive wakeups

6/18/16 5:04:11.000 PM kernel[0]: stampWait: Overflowed checking for stamp 0x3a8491 on MAIN ring: called from 

6/18/16 5:04:11.000 PM kernel[0]: timestamp = 0x3a8490

6/18/16 5:04:11.000 PM kernel[0]: ****  Debug info for apparent hang in MAIN graphics engine  ****

6/18/16 5:04:11.000 PM kernel[0]: ring head    = 0xff6018ec, wrap count = 0x7fb

6/18/16 5:04:11.000 PM kernel[0]: ring tail    = 0x00001b20 ring control = 0x00003001   enabled, auto report disabled, not waiting, semaphore not waiting, length = 0x004 4KB pages

6/18/16 5:04:11.000 PM kernel[0]: timestamp = 0x3a8490

```

**Comment by v-fedorov** [comment]
yep every time,
I invited you to a project.

to reproduce download gfxCardStatus 2.3 https://gfx.io/
make sure to select "integrated only" before opening up the Lab

**Comment by aaronkennedy** [comment]
Does it still happen when the simulator window is closed?

**Comment by v-fedorov** [comment]
Yeah I tested it without simulator as well. 

I think it has to do with what's being used to draw the gesture item in the sidebar. 

I can open the states.zing in an editor and successfully see the page after removing all gestures. 

There is also no issue adding new states to a blank states.zing

**Comment by aaronkennedy** [comment]
I don't understand what you mean by "gesture item in the sidebar". Do you mean the list of behaviours?

**Comment by v-fedorov** [comment]
Oh crap yeah I meant behaviors dude sorry about that.

**Comment by aaronkennedy** [comment]
How about when you view the behaviours with the code editor showing instead of to states editor? Does that work fine?

**Comment by v-fedorov** [comment]
Yeah that works, didn't even notice that tab in the code editor till now :)

**Comment by v-fedorov** [comment]
Also if it helps, opening Window > Inspector causes the same issue

**Comment by aaronkennedy** [comment]
Thanks for helping track this down.

I've added a few debugging options to the latest labs. If you can update, please try toggling the options under the "Zing Elements Lab -> Debug" menu to see if they fix the problem. Start with "Disable antialiasing" and then if it still freezes with antialiasing disabled, try "Disable vectors".

**Comment by v-fedorov** [comment]
Thanks for the quick patch!
Disabling only antialiasing fixes it

**Comment by aaronkennedy** [comment]
Great. The latest build should now automatically disable vector antialiasing on your GPU class. Let me know if this problem recurs.
