### ISSUE TITLE
Open Source Documentation?

### ISSUE THREAD

**Issue by v-fedorov** [aaronkennedy/ZingElements#480]
Is it possible to open source the Documentation section inside the app?

There are some examples id love to see the source for and also be able to contribute to any undocumented logic

**Comment by aaronkennedy** [comment]
I have no philosophical objection to making the docs and examples available, but it is a bit of a hassle to bundle it in a way that would be generally useful. Which examples do you think would be interesting?

**Comment by v-fedorov** [comment]
Would be nice to have a few examples with Gestures.Pan and Interaction.Drag.

In general even a few more open sourced projects would be useful. Or a list of zing share snippets in the github readme/wiki
