### ISSUE TITLE
Ability to stop device going to sleep/auto locking

### ISSUE THREAD

**Issue by designker** [aaronkennedy/ZingElements#502]
Zing Preview has the power to stop the device going to sleep. Would it be possible to access this in a normal zing app? The use case is a new feature based on how Destiny now constantly drops engrams that quickly fill up your inventory. So an engram farm mode will scan your inventory every minute and move items out the way so you can pick up even more engrams.

Yes I know we are sad nerd losers. But picking up loot is so much fun!

**Comment by aaronkennedy** [comment]
This just seems too special purpose for Zing. You can use the new System.broadcastMessage() API to easily communicate with native code and do it there if needed.
