### ISSUE TITLE
Zing Preview & Zing Labs Incompatible

### ISSUE THREAD

**Issue by Mark-Diedericks** [aaronkennedy/ZingElements#503]
Hi,

When attempting to connect my Samsung Galaxy S5 (Ver. "Android 6.0.1") running Zing Preview (Ver. "Beta - 44b9d57") to Zing Elements Lab (Ver. "1.0.8-1-g9157764"), the following error is shown in the "Issues" tab of the Zing Elements Lab;

![zingerror](https://cloud.githubusercontent.com/assets/18547013/19010336/e2f101f8-87c1-11e6-867c-42a220239db7.png)

When clicking on the provided link (http://www.zingelements.com/findCompatibleLabs.html?protocol=internal) it simply states that there are no two compatible versions for the protocol type of internal. I assume this simply means the functionality hasn't been developed.

Other information:
Running Zing Elements Lab, Free Trial
macOS Sierra (10.12)
And if it makes any difference the mac model is 'iMac 11,2" or "EMC2389"

**Comment by aaronkennedy** [comment]
Based on the versions you specify, it looks like you're trying to run a release build of the mac software with a beta build of the device software. This isn't supported.

Try updating to the latest beta version of Studio here (https://www.zingstudio.io/next.html) and the latest beta version of preview here (https://play.google.com/apps/testing/com.zingelements.ZingViewer).

**Comment by Mark-Diedericks** [comment]
Thank you very much for your help.
